feature/95/write test for PageWrapper component
Space2Study-UA-1125/frontEnd pull request #116
Opened 2024-02-13 14:43 UTC by Wiret02

Wrote an test for PageWrapper component
![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/60313835/173dab62-765e-46ca-b468-903b552c8198)

2024-02-13 16:18 UTC, iva-stasia approved these changes

2024-02-13 16:23 UTC, holus-bolus approved these changes

2024-02-13 17:01 UTC, StasRusnak1 approved these changes

2024-02-14 09:15 UTC, VictoriaRodik approved these changes

2024-02-15 15:01 UTC, vlad-khrychov requested changes

2024-02-15 15:01 UTC, vlad-khrychov commented on tests/unit/components/page-wrapper/PageWrapper.spec.jsx
Add `describe` as in all other tests.

2024-02-15 15:01 UTC, vlad-khrychov commented on tests/unit/components/page-wrapper/PageWrapper.spec.jsx
> +  const { getByText } = render(
Maybe call render in `beforeEach`?

2024-02-15 15:01 UTC, vlad-khrychov commented on tests/unit/components/page-wrapper/PageWrapper.spec.jsx
> +  unmount()
Add expect. We can check that `childText` will not be in the document.

2024-02-15 20:40 UTC, ashfox21 approved these changes

2024-02-16 12:08 UTC, vlad-khrychov approved these changes
You can merge after deleting of 1 row.

2024-02-16 12:08 UTC, vlad-khrychov commented on tests/unit/components/page-wrapper/PageWrapper.spec.jsx
> +import { beforeEach, describe } from 'vitest'
```suggestion
```

2024-02-16 13:30 UTC, merged