Bugfix/102/1 write unit test for subjects page
Space2Study-UA-1125/frontEnd pull request #120
Opened 2024-02-14 06:41 UTC by holus-bolus

Created unit tests for the Subjects page

![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/93076661/175f3a69-59d7-4482-bfc1-a8e791be56af)

2024-02-14 09:14 UTC, VictoriaRodik approved these changes

2024-02-14 14:19 UTC, StasRusnak1 approved these changes

2024-02-15 11:40 UTC, Wiret02 approved these changes

2024-02-16 19:21 UTC, iaremchuk approved these changes
Just a reminder to delete comments and change 'test' to 'it'.

2024-02-17 09:07 UTC, holus-bolus commented
> Just a reminder to delete comments and change 'test' to 'it'.

What's the problem with the comment? Couldn't we comment on our code?

2024-02-19 13:02 UTC, vlad-khrychov requested changes
Again. If i understand i need to look only at `tests/unit/pages/subjects/Subjects.spec.jsx` but i see a lot of files in this PR.

2024-02-19 13:02 UTC, vlad-khrychov commented on tests/unit/pages/subjects/Subjects.spec.jsx
This test should be easier if you mock `PageWrapper` component.

2024-02-19 14:42 UTC, holus-bolus commented on tests/unit/pages/subjects/Subjects.spec.jsx
@vlad-khrychov added the PageWrapper mock

2024-02-20 08:21 UTC, closed without merging