unit test for ImgTitleDescription component
Space2Study-UA-1125/frontEnd pull request #123
Opened 2024-02-14 13:05 UTC by VictoriaRodik

![img-title-description-unit-test-coverage](https://github.com/Space2Study-UA-1125/frontEnd/assets/127215334/17336ec9-e769-4825-831e-83888e186560)

2024-02-14 14:22 UTC, StasRusnak1 approved these changes

2024-02-14 19:38 UTC, iva-stasia approved these changes

2024-02-15 11:42 UTC, Wiret02 approved these changes

2024-02-15 18:15 UTC, OliaHrytsak approved these changes

2024-02-16 12:20 UTC, vlad-khrychov requested changes
All is well but we should mock all nested components for unit tests.

2024-02-16 12:20 UTC, vlad-khrychov commented on tests/unit/components/img-title-description/ImgTitleDescription.spec.jsx
Mock `TitleWithDescription` component.

2024-02-17 12:21 UTC, VictoriaRodik commented on tests/unit/components/img-title-description/ImgTitleDescription.spec.jsx
I've mocked the component but pulled previous commits from develop...

2024-02-19 13:30 UTC, vlad-khrychov approved these changes

2024-02-19 13:31 UTC, holus-bolus approved these changes

2024-02-19 13:34 UTC, merged