Implemented a unit test for FindOffers page
Space2Study-UA-1125/frontEnd pull request #129
Opened 2024-02-15 16:43 UTC by vldkk

![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/126193367/24366f51-907b-4ebe-a6b6-771abfc0a120)
![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/126193367/faf13b18-076d-418f-8e76-2c93aa150c10)

2024-02-15 16:54 UTC, VictoriaRodik approved these changes

2024-02-15 16:55 UTC, holus-bolus approved these changes

2024-02-15 20:37 UTC, StasRusnak1 approved these changes

2024-02-16 07:52 UTC, OliaHrytsak approved these changes

2024-02-16 12:17 UTC, vlad-khrychov requested changes
In issue we have 2 items, so at least 2 tests must be available

2024-02-16 12:17 UTC, vlad-khrychov commented on tests/unit/pages/find-offers/FindOffers.spec.jsx
> +import { it } from 'vitest'
```suggestion
```

2024-02-16 12:17 UTC, vlad-khrychov commented on tests/unit/pages/find-offers/FindOffers.spec.jsx
We need to mock `PageWrapper` component.

2024-02-20 18:19 UTC, vldkk commented on tests/unit/pages/find-offers/FindOffers.spec.jsx
> +import { it } from 'vitest'
Changed it, check, please.

2024-02-20 18:20 UTC, vldkk commented on tests/unit/pages/find-offers/FindOffers.spec.jsx
Sure) Added a mock, could you check, please?

2024-02-21 13:57 UTC, vlad-khrychov approved these changes

2024-02-21 14:59 UTC, merged