Added test for AccordionWithImage component
Space2Study-UA-1125/frontEnd pull request #131
Opened 2024-02-15 20:49 UTC by StasRusnak1

Description: Imitate user click on title and it should open content of it
![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/49125203/5e6d3563-90c5-437d-8e38-c976ff3956a8)

2024-02-16 07:55 UTC, OliaHrytsak approved these changes

2024-02-16 08:35 UTC, VictoriaRodik approved these changes

2024-02-16 12:39 UTC, iva-stasia approved these changes

2024-02-16 19:07 UTC, iaremchuk approved these changes

2024-02-19 13:35 UTC, vlad-khrychov requested changes
Please add test to check that not opened item (`Description 1`) is not in the document. 
Also we can add test to check what render before click - it should not render `Description 2` before click.

2024-02-20 14:16 UTC, online-marathon approved these changes

2024-02-21 13:32 UTC, merged