write 104 unit test
Space2Study-UA-1125/frontEnd pull request #134
Opened 2024-02-16 12:53 UTC by ashfox21

Wrote three tests.
1. Whether the component and components passed to it as props are rendered correctly.
2. Whether the functions of opening and closing the component work.
3. Whether hiding styles are applied if isHiding is true.
Coverage 100%
![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/47937700/5600ca0f-5f92-460c-8af7-2021185a9495)

2024-02-16 19:04 UTC, iaremchuk approved these changes

2024-02-17 17:01 UTC, VictoriaRodik approved these changes

2024-02-19 09:19 UTC, Wiret02 approved these changes

2024-02-19 10:19 UTC, holus-bolus commented
![test-path](https://github.com/Space2Study-UA-1125/frontEnd/assets/93076661/a71c7aa3-f395-4031-90a0-109028e3703b)
Would you mind trying to change the path for the component?

2024-02-19 10:20 UTC, holus-bolus commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +import AppPopover from '../../../../src/components/app-popover/AppPopover'
Please try to change the component path

2024-02-19 10:24 UTC, iva-stasia requested changes

2024-02-19 10:24 UTC, iva-stasia commented on src/components/app-popover/AppPopover.jsx
> +    <Box data-testid='anchor' ref={anchorEl}>
Instead of adding `data-testid`, try to mock the `Box` component as well.

2024-02-19 10:24 UTC, iva-stasia commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +  const childrenComponent = <div className='test'>Children</div>
Why do you need this `className='test'` here?

2024-02-19 10:24 UTC, iva-stasia commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +    it('Component is rendered correctly', () => {
The description of the test should sound as a continuation of the `it`. Something like `it(should correctly render the component)`. Read [here](https://daily-dev-tips.com/posts/jest-test-vs-it/) more.

2024-02-19 10:24 UTC, iva-stasia commented on tests/unit/components/app-popover/AppPopover.spec.jsx
Do you think it's necessary to nest one "describe" within another in your case? I believe it only complicates the test. You can mock outside the `describe` block.

2024-02-19 12:25 UTC, OliaHrytsak commented
Test looks very complicated and is hard to reading.
You can use this data-testId to finde open popover
![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/127191734/9516acd2-7145-4598-9f4a-1886c8ca2a58)

 I think you should ask mentor, how to make this test simplier!

2024-02-19 16:17 UTC, ashfox21 commented on tests/unit/components/app-popover/AppPopover.spec.jsx
I structure my tests using two describe blocks because I need to provide different props when rendering components. This helps me avoid code duplication and ensures a cleaner and more organized test structure.

2024-02-19 16:17 UTC, ashfox21 commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +import AppPopover from '../../../../src/components/app-popover/AppPopover'
Thank you for bringing this to my attention. I've made the necessary changes in the new commit and will adhere to this approach going forward.

2024-02-19 16:17 UTC, ashfox21 commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +  const childrenComponent = <div className='test'>Children</div>
Understood, I'll remove that part.

2024-02-19 16:17 UTC, ashfox21 commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +    it('Component is rendered correctly', () => {
Thanks for the provided information. I've updated the test names to be more appropriate.

2024-02-19 16:17 UTC, ashfox21 commented on src/components/app-popover/AppPopover.jsx
> +    <Box data-testid='anchor' ref={anchorEl}>
I removed the unnecessary test-id but kept 'initial'. I believe mocking the Box component would overly complicate testing due to the presence of three Box components with varying levels of nesting.

2024-02-19 18:14 UTC, OliaHrytsak approved these changes

2024-02-19 23:25 UTC, iaremchuk approved these changes

2024-02-20 11:18 UTC, holus-bolus approved these changes

2024-02-20 12:31 UTC, iva-stasia commented on tests/unit/components/app-popover/AppPopover.spec.jsx
In any case, I don't see how it can help here. You can write the mock and props outside the `describe` block and then use them in two separate `describe` blocks. At any rate, we can achieve the same result with different approaches. Good job!

2024-02-20 12:32 UTC, iva-stasia approved these changes

2024-02-20 14:35 UTC, online-marathon requested changes
This is a very difficult test, but I think we can allow it after small refactoring.

2024-02-20 14:35 UTC, online-marathon commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +import React from 'react'
```suggestion
```

2024-02-20 14:35 UTC, online-marathon commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +      default: function MockOpenButton(props) {
```suggestion
      default: function (props) {
```

2024-02-20 14:35 UTC, online-marathon commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +        <AppPopover {...props} hideElem={false}>
`props` are difined in another `describe`

2024-02-20 14:35 UTC, online-marathon commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +      default: function MockOpenButton(props) {
maybe we should destructure all `props` fields here? Like
```suggestion
      default: function MockOpenButton({onClose, open, ...}) {
```

2024-02-20 14:35 UTC, online-marathon commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +                console.log(props.open)
before merge 
```suggestion
```

2024-02-21 14:10 UTC, vlad-khrychov commented on tests/unit/components/app-popover/AppPopover.spec.jsx
> +  })
Let`s delete `beforeEach`, because we have 73th line, that breaks isolation of tests.

2024-02-22 10:27 UTC, vlad-khrychov approved these changes
So, `beforeEach` is running between different `describe`. And second describe is not isolated. I think it is not best think. But lets merge this PR to improve code coverage.

2024-02-22 10:44 UTC, merged