Bugfix/100/write unit test for languagestep container
Space2Study-UA-1125/frontEnd pull request #158
Opened 2024-02-20 08:13 UTC by holus-bolus

Created the unit tests for the LanguageStepContainer component

![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/93076661/c56d7788-b831-405c-96d8-b3d65fb0b87e)

Added the looking for the component via text, vot by the datatest-id

2024-02-20 09:38 UTC, Wiret02 approved these changes

2024-02-21 11:52 UTC, OliaHrytsak approved these changes

2024-02-22 08:39 UTC, iva-stasia approved these changes

2024-02-22 08:39 UTC, iva-stasia commented on tests/unit/containers/tutor-home-page/language-step/LanguageStep.spec.jsx
> +    <div data-testid='language-step-container'>{children}</div>
Why do you need `data-testid` here if you don't use it?

2024-02-22 08:42 UTC, iva-stasia requested changes

2024-02-22 08:42 UTC, iva-stasia commented on tests/unit/containers/tutor-home-page/language-step/LanguageStep.spec.jsx
> +import '@testing-library/jest-dom'
This import seems unnecessary. Please delete it.

2024-02-24 09:47 UTC, iva-stasia approved these changes

2024-02-26 12:50 UTC, VictoriaRodik approved these changes

2024-02-27 11:13 UTC, vlad-khrychov approved these changes

2024-02-27 13:13 UTC, merged