Created NoResultsFound component and added test
Space2Study-UA-1125/frontEnd pull request #163
Opened 2024-02-21 18:09 UTC by StasRusnak1

Description: Implement "Sorry, no results found" block that will be displayed if there are no categories matching the search
![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/49125203/5652cf32-9307-45fa-b685-3909065d088c)
![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/49125203/8889c6c8-bd8b-4818-b904-15b9b1630b3b)
![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/49125203/e9021ec8-8874-44fc-9a43-2b0fde257df5)

2024-02-21 20:12 UTC, VictoriaRodik approved these changes

2024-02-22 07:54 UTC, OliaHrytsak commented
I think, you  should test, that after clicking on button, this block don't display.

2024-02-22 08:43 UTC, holus-bolus approved these changes
good job

2024-02-22 09:05 UTC, ashfox21 approved these changes

2024-02-22 09:08 UTC, iva-stasia requested changes

2024-02-22 09:08 UTC, iva-stasia commented on tests/unit/components/no-results-found/NoResultsFound.spec.jsx
Some MUI components are used inside the component. As I understand it, we need to mock all possible child components. Please try to do so.

2024-02-24 09:49 UTC, iva-stasia approved these changes

2024-02-26 14:59 UTC, online-marathon approved these changes

2024-02-27 09:19 UTC, merged