Bugfix/164/create unit tests for the signup form
Space2Study-UA-1125/frontEnd pull request #165
Opened 2024-02-22 13:56 UTC by holus-bolus

Added unit tests for the signup form
![signup-form-test-3](https://github.com/Space2Study-UA-1125/frontEnd/assets/93076661/3dc20c61-c633-4e5a-a082-0486f1bd2bc6)
![signup-form-test-4](https://github.com/Space2Study-UA-1125/frontEnd/assets/93076661/2daf5911-124b-4f84-a280-5523f1cfe461)
![signup-form-test-coverage](https://github.com/Space2Study-UA-1125/frontEnd/assets/93076661/f5a5e6fb-b5b4-4663-87a6-d8a1ba3d966a)
![signup-form-test-1](https://github.com/Space2Study-UA-1125/frontEnd/assets/93076661/49f92082-5f34-4403-9388-42993ee62039)
![signup-form-test-2](https://github.com/Space2Study-UA-1125/frontEnd/assets/93076661/0487b283-53b2-4b38-8bbe-3e7f2ac6adfd)
![signup-dialog-unit](https://github.com/Space2Study-UA-1125/frontEnd/assets/93076661/1d754e58-9a5e-4881-be55-c3f1e0685e4d)

2024-02-23 13:02 UTC, iaremchuk approved these changes

2024-02-24 15:52 UTC, StasRusnak1 approved these changes

2024-02-25 11:32 UTC, iva-stasia requested changes

2024-02-25 11:32 UTC, iva-stasia commented on src/containers/guest-home-page/signup-form/SignupForm.jsx
> +          data-testid='firstName-input'
I don't see where you are using this `data-testid`. If you need to find this element, you can use `getByLabelText()`. Same for all changed fields.

2024-02-25 11:32 UTC, iva-stasia commented on tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.jsx
> +vi.mock('react-i18next', () => ({
This function is already mocked. Pay attention to the `setup-tests.js` file.

2024-02-25 11:32 UTC, iva-stasia commented on tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.jsx
> -  it('should submit form', async () => {
I don't see a fixed version of this failed test. Are you sure you fixed it?

2024-02-26 09:20 UTC, holus-bolus commented on tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.jsx
> -  it('should submit form', async () => {
![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/93076661/9f7b28ac-1938-40d2-b0ea-cd648a56fe77)
I deleted this test, because even without it the form has 100% coverage

2024-02-26 09:20 UTC, holus-bolus commented on tests/unit/containers/guest-home-page/signup-form/SignupForm.spec.jsx
> +vi.mock('react-i18next', () => ({
Done, thanks

2024-02-26 12:52 UTC, VictoriaRodik approved these changes

2024-02-26 17:00 UTC, iva-stasia approved these changes

2024-02-27 07:36 UTC, Wiret02 approved these changes

2024-02-27 11:11 UTC, vlad-khrychov approved these changes

2024-02-27 13:32 UTC, merged