Feature/198/closing confirmation pop up window for the stepper
Space2Study-UA-1125/frontEnd pull request #206
Opened 2024-03-01 11:15 UTC by holus-bolus

Created the confirmation modal window for the stepper. Whether the user is trying to close the modal window, he sees the confirmation modal. Depending on the choice we stay on the page or we close the stepper

![image](https://github.com/Space2Study-UA-1125/frontEnd/assets/93076661/e5edcbf4-aea6-45e7-a4ef-5e6be80b51ae)

2024-03-01 12:20 UTC, iva-stasia requested changes
I believe you don't need so many changes at all.
Just use the `useConfirm` hook in the `UserStepsWrapper` component:
```javascript
const { setNeedConfirmation } = useConfirm()

useEffect(() => {
  setNeedConfirmation(true)
}, [setNeedConfirmation])
```

<img width="1148" alt="image" src="https://github.com/Space2Study-UA-1125/frontEnd/assets/110097862/96e90ec5-b3ee-4c37-ab27-7a02890d8c4a">

To me, it looks like we achieve the same result with a couple of code lines.
And the message from the existing confirmation modal makes more sense, since the user knows what will happen if they close the step.
If I got something wrong, please let me know.

2024-03-01 13:28 UTC, holus-bolus commented
> I believe you don't need so many changes at all. Just use the `useConfirm` hook in the `UserStepsWrapper` component:
> 
> ```js
> const { setNeedConfirmation } = useConfirm()
> 
> useEffect(() => {
>   setNeedConfirmation(true)
> }, [setNeedConfirmation])
> ```
> 
> <img alt="image" width="1148" src="https://private-user-images.githubusercontent.com/110097862/309255832-96e90ec5-b3ee-4c37-ab27-7a02890d8c4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTk5NTcsIm5iZiI6MTcwOTI5OTY1NywicGF0aCI6Ii8xMTAwOTc4NjIvMzA5MjU1ODMyLTk2ZTkwZWM1LWIzZWUtNGMzNy1hYjI3LTdhMDI4OTBkOGM0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxMzI3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjhlMjAxN2RmZTFmOTQ5ZmNmNmRlNGU2ZTIxYjNkMzAyOTQ0NWRjZWVmZDcyY2I0OTUxNjMyMWViYjhhMDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l1FBZrKfpIG-QKIqF7yznGbHFniX-_4kZqx6ZlIKAa4">
> To me, it looks like we achieve the same result with a couple of code lines. And the message from the existing confirmation modal makes more sense, since the user knows what will happen if they close the step. If I got something wrong, please let me know.

Yes, thank you I changed the logic

2024-03-01 13:42 UTC, Wiret02 approved these changes

2024-03-01 14:56 UTC, VictoriaRodik approved these changes

2024-03-03 08:21 UTC, iaremchuk approved these changes

2024-03-04 08:37 UTC, ashfox21 approved these changes

2024-03-04 10:11 UTC, vldkk approved these changes

2024-03-04 11:27 UTC, iva-stasia approved these changes

2024-03-04 14:06 UTC, vlad-khrychov approved these changes

2024-03-04 15:24 UTC, merged